### ISSUE TITLE
daily run failed with "Not an ARRAY reference" error

### ISSUE THREAD

**Issue by bennettpeter** [garybuhrmaster/tv_grab_zz_sdjson_sqlite#7] opened 2017-04-14 14:21 UTC
This morning my daily run failed with the error
Not an ARRAY reference at /opt/mythtv/bin/tv_grab_zz_sdjson_sqlite line 1393.
I updated to the latest from github and the error still happens with a different line number
Not an ARRAY reference at /opt/mythtv/bin/tv_grab_zz_sdjson_sqlite line 1693.

**Comment by garybuhrmaster** [comment] 2017-04-14 14:39
The problem is malformed upstream data (it does not match their defined data definition).  I will report an example to SchedulesDirect for their resolution.

I will also think about the implication of adding code to validate that each and every upstream element is properly formed, but AFAIK SchedulesDirect has never provided a full schema for their data (and I really do not want to be trying to guess what they are doing).

**Comment by garybuhrmaster** [comment] 2017-04-14 14:45
It turns out that Schedules Direct made a change yesterday, and it now creates invalid videoProperties.

Sorry.

**Comment by garybuhrmaster** [comment] 2017-04-14 15:31
Schedules Direct has reported that their upstream changed things in such a way that the Schedules Direct ingest was broken which cascaded down.  Schedules Direct has updated their codes, and is regenerating their schedules.

And while it is of no consolation, it impacted a number of independent tools that were using the Schedule Direct JSON feeds.

**Comment by garybuhrmaster** [comment] 2017-04-14 18:15
Source data fixed upstream (it might take a bit longer to roll out for some people).

I am going to close this issue as an upstream issue.  Thanks for the notification.

**Closed by garybuhrmaster** 2017-04-14 18:15 UTC

**Comment by bennettpeter** [comment] 2017-04-14 18:34
Thank you for sorting this out so quickly :)
